events {}
http {
  server {
    listen $PORT;
    location / {
      proxy_pass https://m3mobile.net;
      proxy_set_header https://m3-mobile.ru/m3mobilenet;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_ssl_server_name on;
    }
  }
}
