events {}
http {
  server {
    listen $PORT;

    location /m3mobilenet/ {
      proxy_pass https://m3mobile.net/;
      proxy_set_header Host m3mobile.net;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Accept-Encoding "";
      proxy_ssl_server_name on;

      # Переписываем ссылки внутри страницы
      sub_filter 'https://m3mobile.net' '/m3mobilenet';
      sub_filter 'http://m3mobile.net' '/m3mobilenet';
      sub_filter_once off;
      sub_filter_types *;
    }
  }
}
